In [45]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler , LabelEncoder
from sklearn.model_selection import train_test_split

In [46]:
# Load Data
df = pd.read_csv("../data/Telco-Customer-Churn.csv")
df.head()

   customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
0  7590-VHVEG  Female              0  ...          29.85        29.85     No
1  5575-GNVDE    Male              0  ...          56.95       1889.5     No
2  3668-QPYBK    Male              0  ...          53.85       108.15    Yes
3  7795-CFOCW    Male              0  ...          42.30      1840.75     No
4  9237-HQITU  Female              0  ...          70.70       151.65    Yes

[5 rows x 21 columns]

In [47]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

In [48]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges  TotalCharges
count    7043.000000  7043.000000     7043.000000   7032.000000
mean        0.162147    32.371149       64.761692   2283.300441
std         0.368612    24.559481       30.090047   2266.771362
min         0.000000     0.000000       18.250000     18.800000
25%         0.000000     9.000000       35.500000    401.450000
50%         0.000000    29.000000       70.350000   1397.475000
75%         0.000000    55.000000       89.850000   3794.737500
max         1.000000    72.000000      118.750000   8684.800000

# Handling Missing Values

In [49]:
df.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [50]:
df.fillna({'TotalCharges': df['TotalCharges'].median() },inplace=True).head()

   customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
0  7590-VHVEG  Female              0  ...          29.85        29.85     No
1  5575-GNVDE    Male              0  ...          56.95      1889.50     No
2  3668-QPYBK    Male              0  ...          53.85       108.15    Yes
3  7795-CFOCW    Male              0  ...          42.30      1840.75     No
4  9237-HQITU  Female              0  ...          70.70       151.65    Yes

[5 rows x 21 columns]

In [51]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

# Feature Engineering 
Creating New Feautres

In [52]:
df['tenure'].min() , df['tenure'].max()
df['tenure']

0        1
1       34
2        2
3       45
4        2
        ..
7038    24
7039    72
7040    11
7041     4
7042    66
Name: tenure, Length: 7043, dtype: int64

In [53]:
df['tenure_group'] = pd.cut(df['tenure'], 
       bins=[-1,12,24,48,73],
       labels= [0,1,2,3],
       include_lowest=True)

In [54]:
df[['tenure','tenure_group']]

      tenure tenure_group
0          1            0
1         34            2
2          2            0
3         45            2
4          2            0
...      ...          ...
7038      24            1
7039      72            3
7040      11            0
7041       4            0
7042      66            3

[7043 rows x 2 columns]

In [55]:
df['tenure_group'].info()

<class 'pandas.Series'>
RangeIndex: 7043 entries, 0 to 7042
Series name: tenure_group
Non-Null Count  Dtype
--------------  -----
7043 non-null   category
dtypes: category(1)
memory usage: 7.0 KB

In [56]:
df['tenure_group'] = df['tenure_group'].astype(float).astype(int)
df['tenure_group'].info()

<class 'pandas.Series'>
RangeIndex: 7043 entries, 0 to 7042
Series name: tenure_group
Non-Null Count  Dtype
--------------  -----
7043 non-null   int64
dtypes: int64(1)
memory usage: 55.2 KB

In [57]:
df['avg_monthly_per_tenure'] = df['TotalCharges'] / (df['tenure'] + 1)

In [58]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn',
       'tenure_group', 'avg_monthly_per_tenure'],
      dtype='str')

# Encoding

In [59]:
df = df.drop('customerID',axis=1)
df.head(3)

   gender  SeniorCitizen Partner  ... Churn  tenure_group avg_monthly_per_tenure
0  Female              0     Yes  ...    No             0              14.925000
1    Male              0      No  ...    No             2              53.985714
2    Male              0      No  ...   Yes             0              36.050000

[3 rows x 22 columns]

In [60]:
binary_cols = ['Partner','Dependents','PhoneService','PaperlessBilling']
for col in binary_cols:
    df[col] = df[col].map({'Yes':1 , "No":0})

df.head(2)

   gender  SeniorCitizen  Partner  ...  Churn  tenure_group  avg_monthly_per_tenure
0  Female              0        1  ...     No             0               14.925000
1    Male              0        0  ...     No             2               53.985714

[2 rows x 22 columns]

In [61]:
df['Churn'] = df['Churn'].map({'Yes':1,"No":0})

In [62]:
df['gender'] = df['gender'].map({'Male':1,"Female":0})

In [69]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   gender                  7043 non-null   int64
 1   SeniorCitizen           7043 non-null   int64
 2   Partner                 7043 non-null   int64
 3   Dependents              7043 non-null   int64
 4   tenure                  7043 non-null   int64
 5   PhoneService            7043 non-null   int64
 6   MultipleLines           7043 non-null   str
 7   InternetService         7043 non-null   str
 8   OnlineSecurity          7043 non-null   str
 9   OnlineBackup            7043 non-null   str
 10  DeviceProtection        7043 non-null   str
 11  TechSupport             7043 non-null   str
 12  StreamingTV             7043 non-null   str
 13  StreamingMovies         7043 non-null   str
 14  Contract                7043 non-null   str
 15  PaperlessBilling        7043 non-null   int64
 16  PaymentMethod           7043 non-null   str
 17  MonthlyCharges          7043 non-null   float64
 18  TotalCharges            7043 non-null   float64
 19  Churn                   7043 non-null   int64
 20  tenure_group            7043 non-null   int64
 21  avg_monthly_per_tenure  7043 non-null   float64
dtypes: float64(3), int64(9), str(10)
memory usage: 1.2 MB

In [71]:
categorical_cols = df.select_dtypes(include=['object','str']).columns.tolist()

In [74]:
for col in categorical_cols:
    le = LabelEncoder()

    df[col] = le.fit_transform(df[col].astype(str))

In [75]:
df.head(2)

   gender  SeniorCitizen  Partner  ...  Churn  tenure_group  avg_monthly_per_tenure
0       0              0        1  ...      0             0               14.925000
1       1              0        0  ...      0             2               53.985714

[2 rows x 22 columns]